### ISSUE TITLE
prepdocs.py 実行時に[SSL: CERTIFICATE_VERIFY_FAILED]エラーが発生する

### ISSUE THREAD

**Issue by M-Itakura** [shohei1029/book-azureopenai-sample#13]
こちらの対処方法を教えて頂けないでしょうか。

C:\Users\xxx\book-azureopenai-sample\aoai-rag>にいる際に、
`./scripts/prepdocs.ps1`
を実行した後、requirements.txtに基づいたinstallが終わり、【prepdocs.py】の実行の際に以下のエラーが出ます。

**エラー**：
azure.core.exceptions.ServiceRequestError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)

**ログ全文**：
Running "prepdocs.py"
Traceback (most recent call last):
  File "C:\Users\xxx\book-azureopenai-sample\aoai-rag\scripts\prepdocs.py", line 458, in <module>
    create_search_index()
  File "C:\Users\xxx\book-azureopenai-sample\aoai-rag\scripts\prepdocs.py", line 261, in create_search_index
    if args.index not in index_client.list_index_names():
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxx\book-azureopenai-sample\aoai-rag\scripts\.venv\Lib\site-packages\azure\core\paging.py", line 123, in __next__
    return next(self._page_iterator)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxx\book-azureopenai-sample\aoai-rag\scripts\.venv\Lib\site-packages\azure\core\paging.py", line 75, in __next__
    self._response = self._get_next(self.continuation_token)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxx\book-azureopenai-sample\aoai-rag\scripts\.venv\Lib\site-packages\azure\search\documents\indexes\_generated\operations\_indexes_operations.py", line 504, in get_next
    pipeline_response: PipelineResponse = self._client._pipeline.run(  # pylint: disable=protected-access
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxx\book-azureopenai-sample\aoai-rag\scripts\.venv\Lib\site-packages\azure\core\pipeline\_base.py", line 230, in run
    return first_node.send(pipeline_request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxx\book-azureopenai-sample\aoai-rag\scripts\.venv\Lib\site-packages\azure\core\pipeline\_base.py", line 86, in send
    response = self.next.send(request)
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxx\book-azureopenai-sample\aoai-rag\scripts\.venv\Lib\site-packages\azure\core\pipeline\_base.py", line 86, in send
    response = self.next.send(request)
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxx\book-azureopenai-sample\aoai-rag\scripts\.venv\Lib\site-packages\azure\core\pipeline\_base.py", line 86, in send
    response = self.next.send(request)
               ^^^^^^^^^^^^^^^^^^^^^^^
  [Previous line repeated 2 more times]
  File "C:\Users\xxx\book-azureopenai-sample\aoai-rag\scripts\.venv\Lib\site-packages\azure\core\pipeline\policies\_redirect.py", line 197, in send
    response = self.next.send(request)
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxx\book-azureopenai-sample\aoai-rag\scripts\.venv\Lib\site-packages\azure\core\pipeline\policies\_retry.py", line 553, in send
    raise err
  File "C:\Users\xxx\book-azureopenai-sample\aoai-rag\scripts\.venv\Lib\site-packages\azure\core\pipeline\policies\_retry.py", line 531, in send
    response = self.next.send(request)
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxx\book-azureopenai-sample\aoai-rag\scripts\.venv\Lib\site-packages\azure\core\pipeline\policies\_authentication.py", line 126, in send
    response = self.next.send(request)
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxx\book-azureopenai-sample\aoai-rag\scripts\.venv\Lib\site-packages\azure\core\pipeline\_base.py", line 86, in send
    response = self.next.send(request)
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxx\book-azureopenai-sample\aoai-rag\scripts\.venv\Lib\site-packages\azure\core\pipeline\_base.py", line 86, in send
    response = self.next.send(request)
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxx\book-azureopenai-sample\aoai-rag\scripts\.venv\Lib\site-packages\azure\core\pipeline\_base.py", line 86, in send
    response = self.next.send(request)
               ^^^^^^^^^^^^^^^^^^^^^^^
  [Previous line repeated 2 more times]
  File "C:\Users\xxx\book-azureopenai-sample\aoai-rag\scripts\.venv\Lib\site-packages\azure\core\pipeline\_base.py", line 119, in send
    self._sender.send(request.http_request, **request.context.options),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxx\book-azureopenai-sample\aoai-rag\scripts\.venv\Lib\site-packages\azure\core\pipeline\transport\_requests_basic.py", line 386, in send
    raise error
azure.core.exceptions.ServiceRequestError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)

**Comment by nohanaga** [comment]
`CERTIFICATE_VERIFY_FAILED` が出る場合、マシン上で設定された SSL 証明書が正しくないことが原因の可能性があります。[StackOverflow](https://stackoverflow.com/questions/35569042/ssl-certificate-verify-failed-with-python3/43855394#43855394) の回答によると、以下を実行することが推奨されています。
```python
pip install --upgrade certifi
```
もしくは、`aoai-rag/scripts/requirements.txt` の一番下に以下の行を追記して `./scripts/prepdocs.ps1` を実行するとどうでしょうか。
```
certifi==2024.2.2
```
