### ISSUE TITLE
Connection error.(リスト8.3)

### ISSUE THREAD

**Issue by TakeshiSuzuki-Givery** [shohei1029/book-azureopenai-sample#14]
リスト8.3のストリーム処理を以下のコードで実行しました。

```
import os
from openai import AzureOpenAI

your_api_endpoint = "〇〇〇〇"
your_api_key = "〇〇〇〇"
your_deployment_id = "〇〇〇〇" 

client = AzureOpenAI(
    azure_endpoint = f"https: //{your_api_endpoint}.openai.azure.com/",
    api_key = your_api_key,
    api_version = "2023-05-15"#固定
)

response = client.chat.completions.create(
    model = your_deployment_id,
    messages = [
        {"role" : "user",
         "content" : "沖縄の魅力を3888文字で紹介してください"},
    ],
    stream=True
)

for chunk in response:
    if chunk.choices[0].delta.role == 'assistant' or chunk.choices[0].finish_reason == 'stop':
        continue
    else:
        delta = chunk.choices[0].delta.content
        print (delta, end='')
```

結果、以下のようなエラーが出ております。
対処法がお分かりでしたら、ぜひ教えて頂けますと幸いです。

ちなみにAzureにはazd auth loginでログインしており、api-key等の変数は指示通りに設定してあります。
また`5.2.3 ローカル開発環境で実行する`は問題なく実行できております。

環境は以下の通りです。
・Mac OS 14.1.1
・Python 3.11

`Traceback (most recent call last):
  File "Documents/donut/book-azureopenai-sample/aoai-flask-sse/8.3/lib/python3.11/site-packages/httpcore/_exceptions.py", line 10, in map_exceptions
    yield
  File "Documents/donut/book-azureopenai-sample/aoai-flask-sse/8.3/lib/python3.11/site-packages/httpcore/_backends/sync.py", line 206, in connect_tcp
    sock = socket.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/socket.py", line 851, in create_connection
    raise exceptions[0]
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/socket.py", line 836, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 61] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "Documents/donut/book-azureopenai-sample/aoai-flask-sse/8.3/lib/python3.11/site-packages/httpx/_transports/default.py", line 66, in map_httpcore_exceptions
    yield
  File "Documents/donut/book-azureopenai-sample/aoai-flask-sse/8.3/lib/python3.11/site-packages/httpx/_transports/default.py", line 228, in handle_request
    resp = self._pool.handle_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "Documents/donut/book-azureopenai-sample/aoai-flask-sse/8.3/lib/python3.11/site-packages/httpcore/_sync/connection_pool.py", line 268, in handle_request
    raise exc
  File "Documents/donut/book-azureopenai-sample/aoai-flask-sse/8.3/lib/python3.11/site-packages/httpcore/_sync/connection_pool.py", line 251, in handle_request
    response = connection.handle_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "Documents/donut/book-azureopenai-sample/aoai-flask-sse/8.3/lib/python3.11/site-packages/httpcore/_sync/connection.py", line 99, in handle_request
    raise exc
  File "Documents/donut/book-azureopenai-sample/aoai-flask-sse/8.3/lib/python3.11/site-packages/httpcore/_sync/connection.py", line 76, in handle_request
    stream = self._connect(request)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "Documents/donut/book-azureopenai-sample/aoai-flask-sse/8.3/lib/python3.11/site-packages/httpcore/_sync/connection.py", line 124, in _connect
    stream = self._network_backend.connect_tcp(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "Documents/donut/book-azureopenai-sample/aoai-flask-sse/8.3/lib/python3.11/site-packages/httpcore/_backends/sync.py", line 205, in connect_tcp
    with map_exceptions(exc_map):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "Documents/donut/book-azureopenai-sample/aoai-flask-sse/8.3/lib/python3.11/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ConnectError: [Errno 61] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "Documents/donut/book-azureopenai-sample/aoai-flask-sse/8.3/lib/python3.11/site-packages/openai/_base_client.py", line 952, in _request
    response = self._client.send(
               ^^^^^^^^^^^^^^^^^^
  File "Documents/donut/book-azureopenai-sample/aoai-flask-sse/8.3/lib/python3.11/site-packages/httpx/_client.py", line 901, in send
    response = self._send_handling_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "Documents/donut/book-azureopenai-sample/aoai-flask-sse/8.3/lib/python3.11/site-packages/httpx/_client.py", line 929, in _send_handling_auth
    response = self._send_handling_redirects(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "Documents/donut/book-azureopenai-sample/aoai-flask-sse/8.3/lib/python3.11/site-packages/httpx/_client.py", line 966, in _send_handling_redirects
    response = self._send_single_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "Documents/donut/book-azureopenai-sample/aoai-flask-sse/8.3/lib/python3.11/site-packages/httpx/_client.py", line 1002, in _send_single_request
    response = transport.handle_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "Documents/donut/book-azureopenai-sample/aoai-flask-sse/8.3/lib/python3.11/site-packages/httpx/_transports/default.py", line 227, in handle_request
    with map_httpcore_exceptions():
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "Documents/donut/book-azureopenai-sample/aoai-flask-sse/8.3/lib/python3.11/site-packages/httpx/_transports/default.py", line 83, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

[上記あと2回繰り返し]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "Documents/donut/book-azureopenai-sample/aoai-flask-sse/8.3/8.3.py", line 14, in <module>
    response = client.chat.completions.create(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "Documents/donut/book-azureopenai-sample/aoai-flask-sse/8.3/lib/python3.11/site-packages/openai/_utils/_utils.py", line 277, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "Documents/donut/book-azureopenai-sample/aoai-flask-sse/8.3/lib/python3.11/site-packages/openai/resources/chat/completions.py", line 590, in create
    return self._post(
           ^^^^^^^^^^^
  File "Documents/donut/book-azureopenai-sample/aoai-flask-sse/8.3/lib/python3.11/site-packages/openai/_base_client.py", line 1240, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "Documents/donut/book-azureopenai-sample/aoai-flask-sse/8.3/lib/python3.11/site-packages/openai/_base_client.py", line 921, in request
    return self._request(
           ^^^^^^^^^^^^^^
  File "Documents/donut/book-azureopenai-sample/aoai-flask-sse/8.3/lib/python3.11/site-packages/openai/_base_client.py", line 976, in _request
    return self._retry_request(
           ^^^^^^^^^^^^^^^^^^^^
  File "Documents/donut/book-azureopenai-sample/aoai-flask-sse/8.3/lib/python3.11/site-packages/openai/_base_client.py", line 1053, in _retry_request
    return self._request(
           ^^^^^^^^^^^^^^
  File "Documents/donut/book-azureopenai-sample/aoai-flask-sse/8.3/lib/python3.11/site-packages/openai/_base_client.py", line 976, in _request
    return self._retry_request(
           ^^^^^^^^^^^^^^^^^^^^
  File "Documents/donut/book-azureopenai-sample/aoai-flask-sse/8.3/lib/python3.11/site-packages/openai/_base_client.py", line 1053, in _retry_request
    return self._request(
           ^^^^^^^^^^^^^^
  File "Documents/donut/book-azureopenai-sample/aoai-flask-sse/8.3/lib/python3.11/site-packages/openai/_base_client.py", line 986, in _request
    raise APIConnectionError(request=request) from err
openai.APIConnectionError: Connection error.`

**Comment by TakeshiSuzuki-Givery** [comment]
解決しました。
`https: //{your_api_endpoint}.openai.azure.com/"`に空白が入っていたのが原因でした。
